### ISSUE TITLE
Wrong picture size in slideshow

### ISSUE THREAD

**Issue by attiss** [DevTeamSCH/kszkepzes-frontend#12]
nem egyforma magasak a képek, valamelyik picit lóg túl a többinél, valamelyik sokat

ha kódból nem lehet megcsinálni jól, akkor meg kellene csinálni mindegyiket ugyanolyan oldalarányúra.

**Comment by barni2000** [comment]
@szakitom vagd le pls az aljukat.

**Comment by barni2000** [comment]
This help http://www.fmwconcepts.com/imagemagick/aspectcrop/index.php
