### ISSUE TITLE
rosszul látható szöveg a slideshow előtt

### ISSUE THREAD

**Issue by attiss** [DevTeamSCH/kszkepzes-frontend#14]
legyen kicsit vastagabb a fehér szöveg körvonala, mert így bántja az ember szemét, a körvonal ne szürke, hanem fekete legyen

**Comment by attiss** [comment]
örülök neki, hogy ezt lezártátok, de még mindig ugyanolyan :D

**Comment by barni2000** [comment]
Talán mert javítottuk csak meg nem frissíttetem a vm-n.

**Comment by barni2000** [comment]
commit: 753ab7f559a998558717fb01b2eb9e32b52862ca
