### ISSUE TITLE
Change redirection URL on login on

### ISSUE THREAD

**Issue by attiss** [DevTeamSCH/kszkepzes-frontend#17]
kszkujonc.sch.bme.hu és ujonc.kszk.bme.hu címekről lesz elérhető az oldal

**Comment by barni2000** [comment]
De meg nincsenek beállítva, amúgy az egyik default irányítson a másikra ha lehet.

**Comment by barni2000** [comment]
@attiss nem inkább bejelentkezéskor?

**Comment by attiss** [comment]
bejelentkezéskor is, az authschban állítsátok át kszkepzes.sch-ról a címet kszkujonc.sch-ra
