### ISSUE TITLE
Exercises

### ISSUE THREAD

**Issue by attiss** [DevTeamSCH/kszkepzes-frontend#18]
A jelentkezős oldalra ez menjen a harmadik szövegdoboz fölé.

"Alább találsz néhány elgondolkodtató kérdést, megoldandó feladatot. A kérdések és feladatok elkészítése opcionális, nem titkolt célunk ezzel a lelkesedés felmérése. A válaszokat a lenti szövegdobozba várjuk a feladatszámok megjelölésével.

1. Szeretnéd kedvenc tantárgyad vik.wiki oldalát elérni, de szomorúan látod, hogy az oldal nem jön be. A Steam pedig hibátlanul megy a háttérben és az emailek is megérkeznek... Szobatársadnak pont megvan a vik.wiki szerverének IP-címe. Csodálkozva látod, hogy a böngésző címsorába írva eléred a kiszolgáló webszervert. Mi lehet a baj?

2. Két előadás közti szünetben úgy döntesz, hogy laptopoddal az index.hu tech cikkeit fogod görgetni. Ám az oldal nem válaszol. Sőt: a régebbi oldalak többsége sem. Ugyanakkor a Facebook, Gmail, de még az egyetemi oldalak többsége is működik. Van valami ötleted mi okozhatja a gondot?

3. Találsz egy értelmetlen szöveget egy honlapon (például: https://static.mbraptor.ml/zebra.html), de feltűnik, hogy két egyenlőségjellel fejeződik be. Nyomozz, s a végeredményt (amit találtál) írd ide!"

Lesz még egy negyedik is, csak azon egyelőre dolgozok.

**Comment by szakitom** [comment]
question is too long

**Comment by attiss** [comment]
?

**Comment by attiss** [comment]
ne a szövegdobozba tegyétek mondom, mert kurvára nem lehet elolvasni,
tegyétek a textarea fölé a kérdéseket

**Comment by barni2000** [comment]
@szakitom @attiss ?

**Comment by barni2000** [comment]
4.?
