### ISSUE TITLE
Cikkek módosítása

### ISSUE THREAD

**Issue by attiss** [DevTeamSCH/kszkepzes-frontend#26]
A cikkek legyenek mégis fordított sorrendben a mostanihoz képest, és a gólyakörtés cikk szövegét módosítsd erre kérlek:

"Február 8-án 10:00-14:00 között velünk is találkozhattok a GólyaKörTén az I épület aulájában. Látogassatok meg, nézzetek körül nálunk!

18:00-20:00 között a Schönherz 105-ös irodájában is várunk benneteket, ahol megtekinthetitek a szervertermünket valamint hálózati központunkat is."

**Comment by barni2000** [comment]
Admin feluletrol modositd

**Comment by barni2000** [comment]
:'(

**Comment by barni2000** [comment]
Sorrend idorend szerint csokkenoben van.

**Comment by barni2000** [comment]
@attiss
