### ISSUE TITLE
Readable news feed with create and modify date.

### ISSUE THREAD

**Issue by barni2000** [DevTeamSCH/kszkepzes-frontend#3]
This is current:
![image](https://user-images.githubusercontent.com/9256038/35773089-90a438c0-0948-11e8-930d-c00f91c3e049.png)

**Comment by szakitom** [comment]
we could check out [items](https://react.semantic-ui.com/views/item#item-example-items)

**Comment by barni2000** [comment]
Its good but not enough.

**Comment by barni2000** [comment]
![image](https://user-images.githubusercontent.com/9256038/36036792-0ffd92ee-0dbb-11e8-9565-55297ea6bdd5.png)

**Comment by barni2000** [comment]
![image](https://user-images.githubusercontent.com/9256038/36038808-faa0557a-0dc0-11e8-8ef6-d9407fbe9ed0.png)
